'use client';

import { PAGES, SYSTEM_INFO, detectIntent, getIntentResponse, JAB_ORIGIN, jabAgeText } from '@/components/ai-agent/system-knowledge';
import type { Lang } from '@/components/ai-agent/system-knowledge';
import { executeJARVISCommand } from './jarvis-commands';

export type AgentToolResult = { success: boolean; data: unknown; error?: string };

export interface AgentHooks {
  /** Navigate the app to an internal route (function calling → tool use). */
  navigate: (route: string) => void;
  /** Returns the data of the current view (JSON/arrays) for analysis. */
  getViewData?: () => unknown | Promise<unknown>;
  /** Human-readable label of the current view. */
  getViewLabel?: () => string;
  onToolStart?: (name: string, args: Record<string, unknown>) => void;
  onToolEnd?: (name: string, result: AgentToolResult) => void;
}

export interface JABAgentResult {
  content: string;
  raw?: string;
  /** Names of the tools that were actually executed. */
  toolCalls: string[];
  /** Navigation requested by the `navegarA` tool. */
  pendingNav?: string;
  /** Report generated by the `generarReporte` tool (ready for export). */
  report?: { format: string; filename: string; content: string; markdown: string };
}

export interface RunAgentOptions {
  message: string;
  lang: Lang;
  userName: string;
  history?: { role: string; content: string }[];
  hooks: AgentHooks;
  viewData?: unknown;
  viewLabel?: string;
  /** Identidad del empleado/usuario logueado (del catálogo RRHH), para que JAB lo conozca. */
  userIdentity?: {
    nombres: string;
    apellidos: string;
    cargo?: string;
    area?: string;
    code?: string;
    fechaIng?: string;
  };
}

const GROQ_API_KEY = process.env.NEXT_PUBLIC_GROQ_API_KEY || '';
const GROQ_URL = 'https://api.groq.com/openai/v1/chat/completions';
const MODEL = 'llama-3.3-70b-versatile';
const MAX_TOOL_ROUNDS = 4;

// ─── Tool schema (OpenAI/Groq function calling) ───
export const AGENT_TOOLS: {
  name: string;
  description: string;
  parameters: Record<string, { type: string; description: string; enum?: string[] }>;
  required?: string[];
}[] = [
  {
    name: 'navegarA',
    description: 'Navega dentro de la aplicación a otra vista/módulo según lo que pida el usuario (RRHH, QA Reports, IT Manager, Agenda, etc.). Úsala cuando el usuario quiera ir a una sección.',
    parameters: {
      ruta: { type: 'string', description: 'Ruta interna de la aplicación. Válidas: /panel, /panel/welcome, /panel/rrhh, /panel/qa-reports, /panel/it-manager, /panel/it-manager/usuarios, /panel/it-manager/ide, /panel/agenda' },
    },
    required: ['ruta'],
  },
  {
    name: 'analizarDatosVista',
    description: 'Analiza los datos JSON/arrays de la vista actual (RRHH, asistencia, reportes QA, inventario, agenda). Entrega métricas, totales, promedios, anomalías y conclusiones accionables.',
    parameters: {
      objetivo: { type: 'string', description: 'Qué se desea analizar: resumen general, anomalías, tendencias, comparativas, conteos' },
    },
  },
  {
    name: 'generarReporte',
    description: 'Redacta un reporte estructurado en Markdown a partir de los datos de la vista actual, listo para exportar (PDF/CSV/JSON). El reporte incluye resumen, métricas clave y recomendaciones.',
    parameters: {
      tema: { type: 'string', description: 'Tema del reporte (ej: "Asistencia de la semana", "Estado de inventario")' },
      formato: { type: 'string', description: 'Formato de exportación deseado: markdown, csv, json, pdf', enum: ['markdown', 'csv', 'json', 'pdf'] },
    },
  },
  {
    name: 'ejecutarComando',
    description: 'Ejecuta un comando JARVIS del sistema: estado del dispositivo (batería, plataforma, red), copiar al portapapeles, abrir URL, lanzar apps, captura de pantalla.',
    parameters: {
      comando: { type: 'string', description: 'Comando como: status, battery, location, ls, cat, copy, paste, screenshot, open <url>, launch <app>, permissions' },
    },
  },
];

function buildSystemPrompt(lang: Lang, userName: string, viewLabel?: string, identity?: RunAgentOptions['userIdentity']): string {
  const now = new Date();
  const dateStr = now.toLocaleDateString(lang === 'es' ? 'es-MX' : 'en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
  const timeStr = now.toLocaleTimeString(lang === 'es' ? 'es-MX' : 'en-US', { hour: '2-digit', minute: '2-digit', hour12: true });

  const toolList = AGENT_TOOLS.map(t =>
    `- ${t.name}(${Object.keys(t.parameters).join(', ')}): ${t.description}`
  ).join('\n');

  const routes = PAGES.map(p => `${p.route} (${p.label[lang]})`).join(', ');

  const identityBlock = identity && (identity.nombres || identity.apellidos)
    ? lang === 'es'
      ? `\nEl usuario logueado es: ${identity.nombres} ${identity.apellidos}${identity.code ? ` (código: ${identity.code})` : ''}${identity.cargo ? `, cargo: ${identity.cargo}` : ''}${identity.area ? `, área: ${identity.area}` : ''}${identity.fechaIng ? `, ingreso: ${identity.fechaIng}` : ''}. Este es un empleado real del catálogo RRHH.`
      : `\nThe logged-in user is: ${identity.nombres} ${identity.apellidos}${identity.code ? ` (code: ${identity.code})` : ''}${identity.cargo ? `, position: ${identity.cargo}` : ''}${identity.area ? `, area: ${identity.area}` : ''}${identity.fechaIng ? `, started: ${identity.fechaIng}` : ''}. This is a real employee from the HR catalog.`
    : '';

  const selfBlock = lang === 'es'
    ? `\nSobre ti (quién eres): ${JAB_ORIGIN.createdLabel}. Llevas ${jabAgeText('es')} de creado. ${JAB_ORIGIN.purposeLabel}`
    : `\nAbout yourself: ${JAB_ORIGIN.createdLabel}. You have been around for ${jabAgeText('en')}. ${JAB_ORIGIN.purposeLabel}`;

  return lang === 'es'
    ? `Eres JAB, un agente de IA con capacidad de acción (function calling) dentro del Sistema de Control Administrativo.
Fecha: ${dateStr}. Hora: ${timeStr}. Usuario: ${userName}. Vista actual: ${viewLabel || 'principal'}.
${identityBlock}
${selfBlock}

Sobre el sistema:
${SYSTEM_INFO.es}

Rutas de navegación disponibles: ${routes}.

HERRAMIENTAS DISPONIBLES:
${toolList}

REGLAS:
- Cuando el usuario pida navegar, usar navegarA. Para análisis de datos de la vista actual, usar analizarDatosVista. Para reportes, usar generarReporte. Para estado del dispositivo, usar ejecutarComando.
- Cuando ejecutes una herramienta, la herramienta devuelve el resultado; responde al usuario resumiendo ese resultado con claridad.
- Nunca inventes datos: si la herramienta no devuelve datos, dilo.
- Si el usuario pregunta quién es o pide datos sobre sí mismo, usa la identidad del usuario indicada arriba.
- Responde SIEMPRE en el idioma del usuario (${lang === 'es' ? 'español' : 'inglés'}). Sé natural, cercano y fluido.`
    : `You are JAB, an AI agent with action capability (function calling) inside the Administrative Control System.
Date: ${dateStr}. Time: ${timeStr}. User: ${userName}. Current view: ${viewLabel || 'main'}.
${identityBlock}
${selfBlock}

About the system:
${SYSTEM_INFO.en}

Available routes: ${routes}.

AVAILABLE TOOLS:
${toolList}

RULES:
- When the user asks to navigate, use navegarA. To analyze the current view data, use analizarDatosVista. For reports, use generarReporte. For device status, use ejecutarComando.
- When you execute a tool, the tool returns a result; reply to the user summarizing that result clearly.
- Never invent data: if the tool returns no data, say so.
- If the user asks who they are or for their own info, use the logged-in user identity provided above.
- Always reply in the user's language. Be natural, warm and fluent.`;
}

interface ChatMsg { role: 'system' | 'user' | 'assistant' | 'tool'; content: string | null; tool_calls?: unknown; tool_call_id?: string }

async function callGroqWithTools(messages: ChatMsg[]): Promise<{ content?: string; tool_calls?: { id: string; function: { name: string; arguments: string } }[] } | null> {
  if (!GROQ_API_KEY) return null;
  try {
    const res = await fetch(GROQ_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${GROQ_API_KEY}` },
      body: JSON.stringify({
        model: MODEL,
        messages: messages.map(m => {
          const out: any = { role: m.role, content: m.content };
          if (m.tool_calls) out.tool_calls = m.tool_calls;
          if (m.tool_call_id) out.tool_call_id = m.tool_call_id;
          return out;
        }),
        max_tokens: 700,
        temperature: 0.5,
        tools: AGENT_TOOLS.map(t => ({
          type: 'function',
          function: {
            name: t.name,
            description: t.description,
            parameters: { type: 'object', properties: t.parameters, required: t.required || [] },
          },
        })),
        tool_choice: 'auto',
      }),
    });
    if (!res.ok) return null;
    const data = await res.json();
    return data?.choices?.[0]?.message || null;
  } catch {
    return null;
  }
}

// ─── Local data analysis (analizarDatosVista) ───
function analyzeViewData(data: unknown, objetivo: string): { summary: string; metrics: Record<string, unknown> } {
  const metrics: Record<string, unknown> = {};
  if (Array.isArray(data)) {
    metrics.tipo = 'arreglo';
    metrics.total_registros = data.length;
    const sample = data[0];
    if (sample && typeof sample === 'object') {
      const keys = Object.keys(sample as Record<string, unknown>);
      metrics.campos = keys;
      const numericKeys = keys.filter(k => typeof (sample as any)[k] === 'number');
      for (const k of numericKeys) {
        const vals = data.map((d: any) => Number(d[k])).filter(v => !Number.isNaN(v));
        if (vals.length) {
          metrics[`min_${k}`] = Math.min(...vals);
          metrics[`max_${k}`] = Math.max(...vals);
          metrics[`promedio_${k}`] = Math.round((vals.reduce((a, b) => a + b, 0) / vals.length) * 100) / 100;
          metrics[`total_${k}`] = vals.reduce((a, b) => a + b, 0);
        }
      }
      const emptyKeys: Record<string, number> = {};
      for (const k of keys) {
        emptyKeys[k] = data.filter((d: any) => d[k] === undefined || d[k] === null || d[k] === '').length;
      }
      metrics.campos_vacios = emptyKeys;
    }
  } else if (data && typeof data === 'object') {
    const obj = data as Record<string, unknown>;
    metrics.tipo = 'objeto';
    metrics.total_entradas = Object.keys(obj).length;
    for (const [k, v] of Object.entries(obj)) {
      if (typeof v === 'number') metrics[`total_${k}`] = v;
    }
  } else {
    metrics.tipo = 'sin_datos';
    metrics.total_registros = 0;
  }

  const summary = `Análisis (${objetivo || 'general'}): ${JSON.stringify(metrics)}`;
  return { summary, metrics };
}

function buildMarkdownReport(tema: string, data: unknown, viewLabel: string): string {
  const now = new Date();
  const analysis = analyzeViewData(data, 'resumen');
  const lines: string[] = [];
  lines.push(`# Reporte: ${tema}`);
  lines.push('');
  lines.push(`- **Fuente de datos:** ${viewLabel || 'Vista actual'}`);
  lines.push(`- **Generado por:** JAB — ${now.toLocaleString()}`);
  lines.push('');
  lines.push('## Resumen');
  lines.push('');
  lines.push(`- Registros analizados: ${analysis.metrics.total_registros ?? 'N/A'}`);
  lines.push(`- Tipo de datos: ${analysis.metrics.tipo ?? 'N/A'}`);
  lines.push('');
  if (analysis.metrics.campos && Array.isArray(analysis.metrics.campos)) {
    lines.push('## Campos');
    lines.push('');
    lines.push(`\`${(analysis.metrics.campos as string[]).join(', ')}\``);
    lines.push('');
  }
  lines.push('## Métricas');
  lines.push('');
  lines.push('| Métrica | Valor |');
  lines.push('| --- | --- |');
  for (const [k, v] of Object.entries(analysis.metrics)) {
    if (k === 'campos' || k === 'campos_vacios') continue;
    lines.push(`| ${k} | ${JSON.stringify(v)} |`);
  }
  lines.push('');
  lines.push('## Recomendaciones');
  lines.push('');
  lines.push('- Revisar los campos con valores vacíos para garantizar la integridad de los datos.');
  lines.push('- Correlacionar métricas clave con metas semanales/mensuales.');
  return lines.join('\n');
}

// ─── Tool implementations ───
async function executeAgentTool(
  name: string,
  args: Record<string, unknown>,
  opts: RunAgentOptions,
): Promise<{ result: AgentToolResult; sideEffects?: Partial<JABAgentResult> }> {
  opts.hooks.onToolStart?.(name, args);

  const viewData = opts.viewData !== undefined ? opts.viewData : (await opts.hooks.getViewData?.());
  const viewLabel = opts.viewLabel || opts.hooks.getViewLabel?.() || '';

  let result: AgentToolResult;
  const sideEffects: Partial<JABAgentResult> = {};

  switch (name) {
    case 'navegarA': {
      const route = String(args.ruta || '').trim();
      const valid = PAGES.some(p => p.route === route) || route === '/panel' || route === '/panel/welcome';
      if (!valid) {
        result = { success: false, data: null, error: `Ruta inválida: ${route}. Rutas válidas: ${PAGES.map(p => p.route).join(', ')}` };
      } else {
        opts.hooks.navigate(route);
        sideEffects.pendingNav = route;
        result = { success: true, data: { ruta: route, navegado: true } };
      }
      break;
    }
    case 'analizarDatosVista': {
      const objetivo = String(args.objetivo || 'general');
      const analysis = analyzeViewData(viewData, objetivo);
      result = { success: true, data: analysis.metrics };
      break;
    }
    case 'generarReporte': {
      const tema = String(args.tema || 'Reporte del sistema');
      const formato = String(args.formato || 'markdown');
      const markdown = buildMarkdownReport(tema, viewData, viewLabel);
      const filename = tema.toLowerCase().replace(/[^a-z0-9áéíóúñ ]/gi, '').trim().replace(/\s+/g, '-') || 'reporte-jab';
      sideEffects.report = { format: formato, filename, content: markdown, markdown };
      result = { success: true, data: { tema, formato, reporte_markdown: markdown, archivo: `${filename}.${formato}` } };
      break;
    }
    case 'ejecutarComando': {
      const comando = String(args.comando || 'status');
      const output = await executeJARVISCommand(comando);
      result = output
        ? { success: true, data: { comando, salida: output } }
        : { success: false, data: null, error: `Comando "${comando}" no reconocido` };
      break;
    }
    default:
      result = { success: false, data: null, error: `Herramienta desconocida: ${name}` };
  }

  opts.hooks.onToolEnd?.(name, result);
  return { result, sideEffects };
}

// ─── Fallback when no API key or API fails ───
function fallbackAgent(opts: RunAgentOptions): JABAgentResult {
  const { message, lang, userName, hooks, viewData } = opts;
  const intent = detectIntent(message, lang);

  if (intent.action === 'navigate' && intent.params?.route) {
    const route = intent.params.route;
    const page = PAGES.find(p => p.route === route);
    if (page) {
      hooks.navigate(route);
      return {
        content: lang === 'es'
          ? `Te llevo a ${page.label.es}...`
          : `Taking you to ${page.label.en}...`,
        toolCalls: ['navegarA'],
        pendingNav: route,
      };
    }
  }

  if (/(analiza|analizar|resumen|resume|m[eé]tricas|metrics|cu[áa]ntos|c[oó]mo va|reporte|report)/i.test(message)) {
    const data = viewData !== undefined ? viewData : (hooks.getViewData ? null : null);
    if (data !== null && data !== undefined) {
      const analysis = analyzeViewData(data, 'general');
      return {
        content: lang === 'es'
          ? `📊 Análisis de la vista actual:\n\n${JSON.stringify(analysis.metrics, null, 2)}`
          : `📊 Analysis of the current view:\n\n${JSON.stringify(analysis.metrics, null, 2)}`,
        toolCalls: ['analizarDatosVista'],
      };
    }
  }

  const response = getIntentResponse(intent, lang, userName);
  return { content: response, toolCalls: [] };
}

export async function runAgent(opts: RunAgentOptions): Promise<JABAgentResult> {
  const { message, lang, userName, history } = opts;

  if (!GROQ_API_KEY) {
    return fallbackAgent(opts);
  }

  const systemPrompt = buildSystemPrompt(lang, userName, opts.viewLabel || opts.hooks.getViewLabel?.(), opts.userIdentity);
  const messages: ChatMsg[] = [
    { role: 'system', content: systemPrompt },
    ...(history || []).slice(-6).map(h => ({ role: h.role as 'user' | 'assistant', content: h.content })),
    { role: 'user', content: message },
  ];

  const toolCalls: string[] = [];
  let pendingNav: string | undefined;
  let report: JABAgentResult['report'];

  for (let round = 0; round < MAX_TOOL_ROUNDS; round++) {
    const res = await callGroqWithTools(messages);
    if (!res) return fallbackAgent(opts);

    if (res.tool_calls && res.tool_calls.length > 0) {
      messages.push({ role: 'assistant', content: res.content || null, tool_calls: res.tool_calls });
      for (const tc of res.tool_calls) {
        let args: Record<string, unknown> = {};
        try { args = JSON.parse(tc.function.arguments || '{}'); } catch {}
        const { result, sideEffects = {} } = await executeAgentTool(tc.function.name, args, opts);
        toolCalls.push(tc.function.name);
        if (sideEffects.pendingNav) pendingNav = sideEffects.pendingNav;
        if (sideEffects.report) report = sideEffects.report;
        messages.push({ role: 'tool', tool_call_id: tc.id, content: JSON.stringify(result) });
      }
      continue;
    }

    return {
      content: res.content || '',
      raw: res.content,
      toolCalls,
      pendingNav,
      report,
    };
  }

  return { content: '', toolCalls, pendingNav, report };
}
